version: '3.4'

services:
  postgres-compose:
    container_name: flask_app-db-1
    image: postgres:12
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=rangris123
      - POSTGRES_DB=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

  flask-compose:
    container_name: flask-container
    image: flask:0.0.6
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - postgres-compose

volumes:
  postgres-data:

    # docker run --name postgres-container -e POSTGRES_PASSWORD=postgres -e POSTGRES_USER=postgres -e POSTGRES_DB=postgres -p 5432:5432 -d postgres:12
    # docker create -p 5000:5000 --name flask-container flask:0.0.6
    # docker build -t flask:0.0.6 .
    # docker compose up -d
